# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0714294eb084f976cd3d2accf0ba581a6f164d0f383fc2dafda43b3cf7f923605d44d466f4b5ee19290292dd959ea6cbc206f49ee83b5ab6e717413fdb06838

test:
  secret_key_base: e41ef85147c250f1d4a34bfa76847ec8125c8fa5b84b184c42d43a2c53eac0b3b7750ad6f6a0c00e093d46ffee586379935c5f0526722f8dbce0f48294be8bc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
